// SPDX-License-Identifier: UNLICENSED
pragma solidity ^0.8.13;

import {Ownable} from "@openzeppelin/contracts/access/Ownable.sol";

/// @title MutualTick
/// @author @0xJilan
/// @notice Mutual Tick option implementation
contract MutualTick is Ownable {
    address public feeCollector; //address who receives fees generated by contract activity
    uint8 public FEE_NUMERATOR = 3; //fee intended for feeCollector expressed in 18 decimals
    uint16 public FEE_DENOMINATOR = 1000; //fee intended for feeCollector expressed in 18 decimals
    uint256 public MIN_BET = 0.001 ether; //minimum amount to bet
    uint256 public MAX_BET = 100 ether; //maximum amount to bet

    /// @notice Calculate fees to be deducted from a given amount
    /// @dev Fee amount by dividing the numerator by the denominator which - e.g: 3/1000 = 0.003 or 0.3% percent;
    /// @param _amount amount between 1e15 & 1e20.
    /// @return fees amount in wei
    function getFeeAmount(uint96 _amount) public view returns (uint256) {
        return _amount * FEE_NUMERATOR / FEE_DENOMINATOR;
    }
}
